# Generated by Django 2.0 on 2017-12-04 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tag', models.CharField(max_length=20, null=True)),
                ('Title', models.CharField(default='untitled', max_length=20)),
                ('Bode', models.TextField(default='')),
                ('CreateTime', models.DateTimeField(auto_now_add=True)),
                ('ChangedTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Essay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pics', models.CharField(max_length=100)),
                ('Text', models.TextField(default='')),
                ('CreateTime', models.DateTimeField(auto_now_add=True)),
                ('ChangedTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('Nick', models.CharField(max_length=20, unique=True)),
                ('Log', models.TextField(default='')),
                ('Icon', models.FilePathField(default='/static/Icon/default.png', max_length=20)),
                ('Psd', models.CharField(max_length=100)),
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tags', models.CharField(max_length=20)),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Users')),
            ],
        ),
        migrations.AddField(
            model_name='essay',
            name='UserId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Users'),
        ),
        migrations.AddField(
            model_name='articles',
            name='UserId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Users'),
        ),
    ]
