# Generated by Django 2.0 on 2017-12-24 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='essay',
            name='ChangedTime',
        ),
    ]
