# Generated by Django 2.0 on 2018-01-06 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180105_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='essay',
            name='UserId',
        ),
        migrations.RemoveField(
            model_name='users',
            name='Log',
        ),
        migrations.DeleteModel(
            name='Essay',
        ),
    ]
