# Generated by Django 2.0 on 2018-01-10 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180106_2355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='Icon',
        ),
    ]
