# Generated by Django 2.0 on 2018-01-23 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_users_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='ChangedTime',
        ),
    ]
