# Generated by Django 2.0 on 2018-01-23 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_articles_changedtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='id',
        ),
        migrations.AlterField(
            model_name='articles',
            name='Title',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
