# Generated by Django 2.0 on 2018-02-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180123_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='UpdateTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
